[package]
name = "openagents"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-files = "0.6.2"
actix-session = { version = "0.8.0", features = ["cookie-session"] }
actix-web-httpauth = "0.8.1"
anyhow = "1.0.75"
askama = "0.12.1"
askama_actix = "0.14.0"
base64 = "0.21.5"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.8", features = ["derive"] }
dotenvy = "0.15.7"
env_logger = "0.10.1"
futures = "0.3.29"
futures-util = "0.3.29"
jsonwebtoken = "9.1.1"
log = "0.4.20"
oauth2 = "4.4.2"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["json", "stream"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
sqlx = { version = "0.7.2", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid"] }
tempfile = "3.8.1"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.4.1"
uuid = { version = "1.5.0", features = ["v4", "serde"] }
mockito = "1.2.0"

[dev-dependencies]
serial_test = "2.0.0"