[package]
name = "openagents"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-files = "0.6"
actix-web = "4"
actix-web-actors = "4.1"
anyhow = "1.0"
askama = { version = "0.12", features = ["with-actix-web"] }
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
dotenv = "0.15"
futures = "0.3"
futures-util = { version = "0.3", features = ["sink"] }
git2 = "0.18"
headers = "0.4"
jsonwebtoken = "9.2"
oauth2 = "4.4"
octocrab = "0.32"
pulldown-cmark = "0.9"
regex = "1.10"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "postgres", "uuid", "chrono"] }
termcolor = "1.4"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.20"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
uuid = { version = "1.6", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3.9"