[package]
name = "openagents"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-web = "4.4"
actix-web-actors = "4.2"
actix-files = "0.6"
actix-cors = "0.6"
env_logger = "0.10"
dotenv = "0.15"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-aux = "4"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
uuid = { version = "1.4", features = ["v4"] }
bitcoin_hashes = "0.12"
secp256k1 = { version = "0.27", features = ["rand", "bitcoin_hashes"] }
lazy_static = "1.4"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "json", "tls-native-tls"] }
config = "0.13"
secrecy = { version = "0.8", features = ["serde"] }
tracing = { version = "0.1", features = ["log"] }
url = "2.4"
